
import Header from '@/components/layouts/header';
import Navbar from '@/components/layouts/nav';
import CustomeStyles from './custome-styles';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div id="__next">   
          {/* <CustomeStyles />      */}
          <Header />
          <Navbar />
          <main className="px-3.5 pt-8 pb-20 lg:px-6 lg:py-10">{children}</main>
        </div>
      </body>
    </html>
  )
}
